let data = {
    "AFG": [
        {
            "continent": "Asia",
            "location": "Afghanistan",
            "date": "2019-12-31",
            "total_cases": 0,
            "new_cases": 0,
            "total_deaths": 0,
            "new_deaths": 0,
            "total_cases_per_million": 0,
            "new_cases_per_million": 0,
            "total_deaths_per_million": 0,
            "new_deaths_per_million": 0,
            "population": 38928341,
            "population_density": 54.422,
            "median_age": 18.6,
            "aged_65_older": 2.581,
            "aged_70_older": 1.337,
            "gdp_per_capita": 1803.987,
            "cvd_death_rate": 597.029,
            "diabetes_prevalence": 9.59,
            "handwashing_facilities": 37.746,
            "hospital_beds_per_thousand": 0.5,
            "life_expectancy": 64.83
        },
        {
            "continent": "Asia",
            "location": "Afghanistan",
            "date": "2020-01-01",
            "total_cases": 0,
            "new_cases": 0,
            "total_deaths": 0,
            "new_deaths": 0,
            "total_cases_per_million": 0,
            "new_cases_per_million": 0,
            "total_deaths_per_million": 0,
            "new_deaths_per_million": 0,
            "stringency_index": 0,
            "population": 38928341,
            "population_density": 54.422,
            "median_age": 18.6,
            "aged_65_older": 2.581,
            "aged_70_older": 1.337,
            "gdp_per_capita": 1803.987,
            "cvd_death_rate": 597.029,
            "diabetes_prevalence": 9.59,
            "handwashing_facilities": 37.746,
            "hospital_beds_per_thousand": 0.5,
            "life_expectancy": 64.83
        },
        {
            "continent": "Asia",
            "location": "Afghanistan",
            "date": "2020-01-02",
            "total_cases": 0,
            "new_cases": 0,
            "total_deaths": 0,
            "new_deaths": 0,
            "total_cases_per_million": 0,
            "new_cases_per_million": 0,
            "total_deaths_per_million": 0,
            "new_deaths_per_million": 0,
            "stringency_index": 0,
            "population": 38928341,
            "population_density": 54.422,
            "median_age": 18.6,
            "aged_65_older": 2.581,
            "aged_70_older": 1.337,
            "gdp_per_capita": 1803.987,
            "cvd_death_rate": 597.029,
            "diabetes_prevalence": 9.59,
            "handwashing_facilities": 37.746,
            "hospital_beds_per_thousand": 0.5,
            "life_expectancy": 64.83
        },
        {
            "continent": "Asia",
            "location": "Afghanistan",
            "date": "2020-01-03",
            "total_cases": 0,
            "new_cases": 0,
            "total_deaths": 0,
            "new_deaths": 0,
            "total_cases_per_million": 0,
            "new_cases_per_million": 0,
            "total_deaths_per_million": 0,
            "new_deaths_per_million": 0,
            "stringency_index": 0,
            "population": 38928341,
            "population_density": 54.422,
            "median_age": 18.6,
            "aged_65_older": 2.581,
            "aged_70_older": 1.337,
            "gdp_per_capita": 1803.987,
            "cvd_death_rate": 597.029,
            "diabetes_prevalence": 9.59,
            "handwashing_facilities": 37.746,
            "hospital_beds_per_thousand": 0.5,
            "life_expectancy": 64.83
        },
        {
            "continent": "Asia",
            "location": "Afghanistan",
            "date": "2020-01-04",
            "total_cases": 0,
            "new_cases": 0,
            "total_deaths": 0,
            "new_deaths": 0,
            "total_cases_per_million": 0,
            "new_cases_per_million": 0,
            "total_deaths_per_million": 0,
            "new_deaths_per_million": 0,
            "stringency_index": 0,
            "population": 38928341,
            "population_density": 54.422,
            "median_age": 18.6,
            "aged_65_older": 2.581,
            "aged_70_older": 1.337,
            "gdp_per_capita": 1803.987,
            "cvd_death_rate": 597.029,
            "diabetes_prevalence": 9.59,
            "handwashing_facilities": 37.746,
            "hospital_beds_per_thousand": 0.5,
            "life_expectancy": 64.83
        },
        {
            "continent": "Asia",
            "location": "Afghanistan",
            "date": "2020-01-05",
            "total_cases": 0,
            "new_cases": 0,
            "total_deaths": 0,
            "new_deaths": 0,
            "total_cases_per_million": 0,
            "new_cases_per_million": 0,
            "total_deaths_per_million": 0,
            "new_deaths_per_million": 0,
            "stringency_index": 0,
            "population": 38928341,
            "population_density": 54.422,
            "median_age": 18.6,
            "aged_65_older": 2.581,
            "aged_70_older": 1.337,
            "gdp_per_capita": 1803.987,
            "cvd_death_rate": 597.029,
            "diabetes_prevalence": 9.59,
            "handwashing_facilities": 37.746,
            "hospital_beds_per_thousand": 0.5,
            "life_expectancy": 64.83
        },
        {
            "continent": "Asia",
            "location": "Afghanistan",
            "date": "2020-01-06",
            "total_cases": 0,
            "new_cases": 0,
            "total_deaths": 0,
            "new_deaths": 0,
            "total_cases_per_million": 0,
            "new_cases_per_million": 0,
            "total_deaths_per_million": 0,
            "new_deaths_per_million": 0,
            "stringency_index": 0,
            "population": 38928341,
            "population_density": 54.422,
            "median_age": 18.6,
            "aged_65_older": 2.581,
            "aged_70_older": 1.337,
            "gdp_per_capita": 1803.987,
            "cvd_death_rate": 597.029,
            "diabetes_prevalence": 9.59,
            "handwashing_facilities": 37.746,
            "hospital_beds_per_thousand": 0.5,
            "life_expectancy": 64.83
        },
        {
            "continent": "Asia",
            "location": "Afghanistan",
            "date": "2020-01-07",
            "total_cases": 0,
            "new_cases": 0,
            "total_deaths": 0,
            "new_deaths": 0,
            "total_cases_per_million": 0,
            "new_cases_per_million": 0,
            "total_deaths_per_million": 0,
            "new_deaths_per_million": 0,
            "stringency_index": 0,
            "population": 38928341,
            "population_density": 54.422,
            "median_age": 18.6,
            "aged_65_older": 2.581,
            "aged_70_older": 1.337,
            "gdp_per_capita": 1803.987,
            "cvd_death_rate": 597.029,
            "diabetes_prevalence": 9.59,
            "handwashing_facilities": 37.746,
            "hospital_beds_per_thousand": 0.5,
            "life_expectancy": 64.83
        },
        {
            "continent": "Asia",
            "location": "Afghanistan",
            "date": "2020-01-08",
            "total_cases": 0,
            "new_cases": 0,
            "total_deaths": 0,
            "new_deaths": 0,
            "total_cases_per_million": 0,
            "new_cases_per_million": 0,
            "total_deaths_per_million": 0,
            "new_deaths_per_million": 0,
            "stringency_index": 0,
            "population": 38928341,
            "population_density": 54.422,
            "median_age": 18.6,
            "aged_65_older": 2.581,
            "aged_70_older": 1.337,
            "gdp_per_capita": 1803.987,
            "cvd_death_rate": 597.029,
            "diabetes_prevalence": 9.59,
            "handwashing_facilities": 37.746,
            "hospital_beds_per_thousand": 0.5,
            "life_expectancy": 64.83
        },
        {
            "continent": "Asia",
            "location": "Afghanistan",
            "date": "2020-01-09",
            "total_cases": 0,
            "new_cases": 0,
            "total_deaths": 0,
            "new_deaths": 0,
            "total_cases_per_million": 0,
            "new_cases_per_million": 0,
            "total_deaths_per_million": 0,
            "new_deaths_per_million": 0,
            "stringency_index": 0,
            "population": 38928341,
            "population_density": 54.422,
            "median_age": 18.6,
            "aged_65_older": 2.581,
            "aged_70_older": 1.337,
            "gdp_per_capita": 1803.987,
            "cvd_death_rate": 597.029,
            "diabetes_prevalence": 9.59,
            "handwashing_facilities": 37.746,
            "hospital_beds_per_thousand": 0.5,
            "life_expectancy": 64.83
        },
        {
            "continent": "Asia",
            "location": "Afghanistan",
            "date": "2020-01-10",
            "total_cases": 0,
            "new_cases": 0,
            "total_deaths": 0,
            "new_deaths": 0,
            "total_cases_per_million": 0,
            "new_cases_per_million": 0,
            "total_deaths_per_million": 0,
            "new_deaths_per_million": 0,
            "stringency_index": 0,
            "population": 38928341,
            "population_density": 54.422,
            "median_age": 18.6,
            "aged_65_older": 2.581,
            "aged_70_older": 1.337,
            "gdp_per_capita": 1803.987,
            "cvd_death_rate": 597.029,
            "diabetes_prevalence": 9.59,
            "handwashing_facilities": 37.746,
            "hospital_beds_per_thousand": 0.5,
            "life_expectancy": 64.83
        },
        {
            "location": "World",
            "date": "2020-06-18",
            "total_cases": 8317573,
            "new_cases": 175841,
            "total_deaths": 450630,
            "new_deaths": 5250,
            "total_cases_per_million": 1067.067,
            "new_cases_per_million": 22.559,
            "total_deaths_per_million": 57.812,
            "new_deaths_per_million": 0.674,
            "population": 7794798729,
            "population_density": 58.045,
            "median_age": 30.9,
            "aged_65_older": 8.696,
            "aged_70_older": 5.355,
            "gdp_per_capita": 15469.207,
            "extreme_poverty": 10,
            "cvd_death_rate": 233.07,
            "diabetes_prevalence": 8.51,
            "female_smokers": 6.434,
            "male_smokers": 34.635,
            "handwashing_facilities": 60.13,
            "hospital_beds_per_thousand": 2.705,
            "life_expectancy": 72.58
        }
    ]
};
//let a = data.AFG;
//console.log(a);
let b = data.AFG[1].continent;
console.log(b);
